spring:
  application:
    name: backend
  profiles:
    active: local
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres}
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  brevo:
    api-key: ${BREVO_API_KEY}
    from-email: ${BREVO_FROM_EMAIL}
    from-name: NorthPay
  frontend:
    url: ${FRONTEND_URL}
    onboarding-path: /onboarding
  storage:
    endpoint: ${SUPABASE_STORAGE_ENDPOINT}
    region: ${SUPABASE_STORAGE_REGION}
    bucket: ${SUPABASE_STORAGE_BUCKET}
    access-key: ${SUPABASE_STORAGE_ACCESS_KEY}
    secret-key: ${SUPABASE_STORAGE_SECRET_KEY}
    public-url-prefix: ${SUPABASE_STORAGE_PUBLIC_PREFIX}
  pusher:
    app-id: ${PUSHER_APP_ID}
    key: ${PUSHER_KEY}
    secret: ${PUSHER_SECRET}
    cluster: ${PUSHER_CLUSTER}

server:
  port: 7860