spring:
  application:
    name: backend
  profiles:
    active: local
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  brevo:
    api-key: ${BREVO_API_KEY}
    from-email: ${BREVO_FROM_EMAIL}
    from-name: NorthPay
  frontend:
    url: ${FRONTEND_URL}
    onboarding-path: /onboarding

server:
  port: 7860