spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres
    username: ${SUPABASE_DB_USER}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

    flyway:
      enabled: true
      locations: classpath:db/migration

server:
  port: 7860